# Generated by Django 3.1.7 on 2021-03-05 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pinguer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ipAddress', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PinguerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(1, 'Activation'), (2, 'Deactivation')])),
                ('event_date', models.DateTimeField()),
                ('pinguer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PIngueandoWebApp.pinguer')),
            ],
        ),
    ]
